### ISSUE TITLE
Why this is no document about how to use it ??

### ISSUE THREAD

**Issue by andersling** [flosch/pongo2#317] opened 2022-12-10 15:44 UTC
Thanks for greate job! 

 But I can't see any document on how to use it , this may make this amazing project USELESS!!

**Comment by aneshas** [comment] 2022-12-18 10:49
I would add +1 to that. I'm trying to evaluate a few templating packages (template inheritance / composition being a deciding factor for me) and while this one seems to be really good, a useful documentation is close to non-existing with a couple of blog posts here and there...

**Comment by adonespitogo** [comment] 2022-12-21 13:47
I found the brief example in the readme to be very promising. But without documentation, this basically renders this library close to being unusable.

**Comment by adpande** [comment] 2022-12-27 16:58
Check this: https://docs.djangoproject.com/en/4.1/topics/templates/
Here is the original documentation on how to use it

**Comment by adonespitogo** [comment] 2022-12-28 12:15
I think this library (and all others) could  really benefit from having an easy to read and getting-started documentation. Really hard for me as a go beginner to start using this library. Coming from Nodejs environment where every library has proper documentations (getting started, installation, usage examples), I find the golang ecosystem lacking in this regard.  Although I've managed to build a simple view engine for my project using examples I found online, it was difficult searching for random articles just to be able to start using it.

I wonder if this is a language culture thing. Since switching to golang and trying to look for libraries to use for my project, many of the common and popular tools have documentations that look like a WIP, if there's any at all. I've written many libraries in many languages myself. A good, understandable documentation was always part of my releases just to reciprocate other OSS devs who also put effort on writing their documentation. I know this is a free software and I'm not in anyway putting pressure on the maintainer to do this for me. I'm just stating my observations.

I'll try to make a PR to add a simple usage example and I hope it can get accepted. It will really help beginners like me to get up to speed.

**Comment by adpande** [comment] 2022-12-29 10:11
Check this as well:

https://docs.djangoproject.com/en/4.1/ref/templates/language/

**Comment by aneshas** [comment] 2022-12-29 11:03
@adpande yes thanks. I assumed that it's probably equivalent to that but still, it might be made more explicit that that's where people should look... And also for Go specific stuff the only alternative is to browse through godoc.

**Comment by flosch** [comment] 2023-02-01 12:33
Duplicate of #36

**Closed by flosch** 2023-02-01 12:33 UTC
